# Generated by Django 4.1.3 on 2023-10-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_recipe_category_alter_recipe_cover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cover",
            field=models.ImageField(upload_to="recipes/covers/%Y/%m/%d/"),
        ),
    ]
